# ============================== Filebeat Configuration ==============================

# Configure the Filebeat inputs
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/spring-boot/application.log
    fields:
      app_id: my-spring-boot-app
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5000"]



