version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/spring-boot/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    hostname: prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    hostname: grafana
    networks:
      - monitoring

  # MongoDB: Stores the graylog metadata and configurations
  mongo:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - graylog
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 10s
      retries: 5

  # Elasticsearch: Stores the log data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    networks:
      graylog:
        aliases:
          - elasticsearch-hostname
    environment:
      - node.name=elasticsearch
      - ELASTIC_PASSWORD=changeme
      - cluster.name=graylog
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5

  # Graylog: The central log management server
  graylog:
    image: graylog/graylog:5.0.0
    container_name: graylog
    networks:
      - graylog
    depends_on:
      elasticsearch:
        condition: "service_started"
      mongo:
          condition: "service_started"

    environment:
      - GRAYLOG_PASSWORD_SECRET=supersecretpasswordsecret
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918  # SHA-256 for 'admin'
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch-hostname:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog

    entrypoint: /usr/bin/tini -- wait-for-it mongo:27017 -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    ports:
      - 9000:9000/tcp   # Graylog web interface and REST API
      - 12201:12201/tcp # GELF
      - 12201:12201/udp # GELF
      - 1514:1514/tcp   # Syslog
      - 1514:1514/udp   # Syslog
    restart: always

    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
volumes:
  grafana-storage:
  mongo_data:
  es_data:
  graylog_journal:


networks:
  monitoring:
    driver: bridge
  graylog:
    driver: bridge
