global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scheme: http
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['app:8080']